### ISSUE TITLE
Configure output directory

### ISSUE THREAD

**Issue by lexon0011** [frhagn/Typewriter#106]
Is it possible to configure the output directory in the template?

I want to add the Typewriter Template (.tst) to my project which includes the models (*.cs). The generated files should be created on a configured path. I need this approach because the target project/path is not part of the Visual Studio solution.

Thank you very much!

**Comment by frhagn** [comment]
Hi @lexon0011,
Configuring the output directory is not possible at the moment. Support for this will be included in Typewriter 2.0.

**Comment by lexon0011** [comment]
Thanks!! Is there a Roadmap when Typewriter 2.0 will be released?

**Comment by SeriousM** [comment]
Not when, but what's included: https://github.com/frhagn/Typewriter/milestones/v2.0

**Comment by LeeCheneler** [comment]
You can configure the output path like so:

```
Template(Settings settings)
{
    settings.OutputFilenameFactory = file =>
    {
        return "dir/filename.ts";
    };
}
```

**Comment by SeriousM** [comment]
> You can configure the output path like so:
> 
> Template(Settings settings)
> {
>     settings.OutputFilenameFactory = file =>
>     {
>         return "dir/filename.ts";
>     };
> }

I wouldn't do that. Regarding to the [Changelog](https://frhagn.github.io/Typewriter/pages/changelog.html) for version 1.3.1:
> Warning
 Changing the output folder using OutputFilenameFactory is NOT supported and can lead to unexpected behaviour resulting in loss of files.

**Comment by LeeCheneler** [comment]
Yeah... I kinda prompted that warning! It was broken in a release 1.3.0, luckily @frhagn was kind enough to put support back in for 1.3.1!! It works fine though. We have a 1 template spewing models out for all our areas and pages into their own directories.

**Comment by lexon0011** [comment]
It is not working with the following configuration:
```
settings.OutputFilenameFactory = file =>
{
     return "../dir/" + file.Name;
};
```
I created the directory "dir" outside of the template directory (.tst). The typewriter create only one file and exit then with the following error:
```
14:57:42.859 ERROR: Error processing queue: Unable to add 'BroadcastAudioType.cs'. A file with that name already exists.
   at EnvDTE.ProjectItems.AddFromFile(String FileName)
   at Typewriter.Generation.Template.SaveFile(File file, String output)
   at Typewriter.Generation.Template.RenderFile(File file)
   at Typewriter.Generation.Controllers.GenerationController.<>c__DisplayClass5_0.<OnTemplateChanged>b__1()
   at Typewriter.Generation.Controllers.EventQueue.ProcessQueue()
```

**Comment by frhagn** [comment]
Hi @lexon0011,
First of all I have to warn you that changing output folder is NOT supported and might result in some very strange behaviour resulting in loss of files! 
However it seems to work for some people so if you want to try it, it's up to you..

I can't really say what the problem is here, but it might work better if you change the directory separator to `\`. Also, `file.Name` is the name of the C# source file so if you want to output TypeScript files you should replace the file extension as well.
```
settings.OutputFilenameFactory = file =>
{
     return @"..\dir\" + file.Name.Replace(".cs", ".ts");
};
```

**Comment by lexon0011** [comment]
I think I will wait to the official supported version. Nevertheless, thanks for your help!

**Comment by LeeCheneler** [comment]
I'm not entirely sure what you issue is. This is how we configure our template exactly:

```
Template(Settings settings)
    {
        settings.IncludeCurrentProject();
        settings.OutputFilenameFactory = file =>
        {
            string area = GetAreaName(file);
            string subArea = GetSubAreaName(file);
            var modelClass = file.Classes.First();
            return $"{area}/Client/ts/{GetCamelCase(subArea)}/twModels/{modelClass.name}.ts";
        };
    }
```
The directory `{area}` is relative to the where the template file is. In our MVC6 project we have a folder `Areas` and within that is the template folders and our specific area folders. 

Also its important to note we use this in aspnetcore projects, not msbuild projects.

**Comment by alan994** [comment]
Are there any progress with this feature request?

**Comment by agustinbcu01** [comment]
This issue was open Mar 26, 2016, Please, did you know when will be ready, 2.0 milestone is at 9%.

**Comment by agustinbcu01** [comment]
@frhagn any update?

**Comment by Macadoshis** [comment]
This workaround is quite dirty but I managed to create my output directory calling ``DirectoryInfo directoryInfo = Directory.CreateDirectory(pathFileName);`` right before returning the fileName;

Full example code :

```cs
// MyProject[.sln]\MyProject.Client\src\app\models\ModelGenerator.tst
Template(Settings settings)
    {
        settings
           .IncludeAllProjects()
           .OutputFilenameFactory = (file) => {
                string[] fileParts = file.FullName.Split('\\');
                Boolean startNamespaceAppending = false;
                string prefixFolder = "";
                string last = fileParts.Last();
                // Extract correct namespace to create corresponding output directory, according to my target Angular/TypeScript project
                foreach (var item in fileParts) {
                    if (!item.Equals(last)) {
                        if (string.Equals(item, "Models", StringComparison.OrdinalIgnoreCase)) {
                            startNamespaceAppending = true;
                        } else if (startNamespaceAppending) {
                            prefixFolder += SpacesFromCamel(item) + "/";
                        }
                    }
                }
                // Extract correct type name depending on its type (class, enum, interface, ...)
                string typeName = "undefined";
                if (file.Classes.Count > 0) {
                    typeName = file.Classes.First().Name;
                } else if (file.Interfaces.Count > 0) {
                    typeName = file.Interfaces.First().Name;
                } else if (file.Enums.Count > 0) {
                    typeName = file.Enums.First().Name;
                }
                string fileName = prefixFolder + SpacesFromCamel(typeName) + ".ts";
                // Creates target directory if it does not exist
                Regex rgx = new Regex("^(.*)(MyProject\\.[\\w\\.]+\\\\Models)(.*)$");
                string pathFileName = Path.GetDirectoryName(file.FullName);
                pathFileName = rgx.Replace(pathFileName, "$1\\MyProject.Client\\src\\app\\models\\" + prefixFolder);
                if (!Directory.Exists(pathFileName)) {
                    DirectoryInfo directoryInfo = Directory.CreateDirectory(pathFileName);
                }
                return fileName;
            };
    }

    /* Transform a C# project directory name to a "typescript/client" directory name (no upper case, etc.)*/
    string SpacesFromCamel(string value)
    {
        if (value.Length > 0)
        {
            var result = new List<char>();
            char[] array = value.ToCharArray();
            foreach (var item in array)
            {
                if (char.IsUpper(item) && result.Count > 0)
                {
                    result.Add('-');
                }
                result.Add(char.ToLower(item));
            }

            return new string(result.ToArray());
        }
        return value;
    }
```

This example will output following cs classes :
_MyProject[.sln]\MyProject.RestInterface\Models\UserManagement\Role\IRole.cs_
_MyProject[.sln]\MyProject.RestInterface\Models\SiteManagement\ISite.cs_
_MyProject[.sln]\MyProject.RestInterface\Models\SiteManagement\DepartmentStatus.cs_

to :
_MyProject[.sln]\MyProject.Client\src\app\models\user-management\role\i-role.ts_
_MyProject[.sln]\MyProject.Client\src\app\models\site-management\i-site.ts_
_MyProject[.sln]\MyProject.Client\src\app\models\site-management\department-status.ts_

Automatically creating directories in tree view if they don't exist.

**Comment by tomaszbroniewski** [comment]
> Not when, but what's included: https://github.com/frhagn/Typewriter/milestones/v2.0

will 2.0 also be under free license?

**Comment by milkotv** [comment]
Greetings. Worked out a way that gets the job done for me. Hope this helps.

You need the following:

- Define a TypeScriptAttribute class 
```
[AttributeUsage(AttributeTargets.Class)]
public class TypeScriptAttribute : Attribute
{
    public string Name { get; set; }    
    public TypeScriptAttribute(string name)
    {
        Name = name;
    }
}
```

- Decorate the classes you want to export to TS with [TypeScript(<name of your TS class>)]]
```
namespace WebApi.Models.Accounts
{
    [TypeScript("AccountsInfo")]
    public class Info
    {
        public int Id { get; set; }
        public string Email { get; set; }
        public int CompanyId { get; set; }
        public string CompanyName { get; set; }
        public string Tag { get; set; }
    }
}
```
- Use the following Template:
```
${
    using Typewriter.Extensions.Types;

    Template(Settings settings)
    {
        settings.OutputFilenameFactory = file =>
        {
            // Get the class with the TypeScript attribute (1 per file, sorry)
            var cl = file.Classes.FirstOrDefault(x => x.Attributes.Any(a => a.Name == "TypeScript"));
            var tsName = cl.Attributes.FirstOrDefault(x => x.Name == "TypeScript")?.Value;
            return $"Scripts/{tsName}.ts";
        };
    }

    string LoudName(Property property)
    {
        return property.FullName;
    }

    string ClassName (Class cl)
    {
        return cl.Attributes.FirstOrDefault(x => x.Name == "TypeScript")?.Value;
    }
}
module WebApi {
    $Classes([TypeScript])[
    // $FullName
    export class $ClassName {
        $Properties[
        // $LoudName
        public $name: $Type = $Type[$Default];]
    }]
}
```

- The files get generated in Scripts folder like so:
![image](https://user-images.githubusercontent.com/11747258/141595665-ecb7e4b6-217f-4def-83c1-4c2fc5471fb5.png)

**Comment by countredbeard** [comment]
I wanted my files to go next to the corresponding CS file in the same folder 
this worked for me without having to find actual project root. Figured it was safe enough to hard code the Project name in this case.

settings.OutputFilenameFactory = file =>
            {
                var index = file.FullName.IndexOf("My.Project.Name");
                var rp = file.FullName.Substring(index);
                rp = rp.Replace("PMy.Project.Name", ".").Replace(".cs", ".dto.ts");
                return rp;
            };
