### ISSUE TITLE
Using 3rd party assembly routines in Custom Methods

### ISSUE THREAD

**Issue by Beej126** [frhagn/Typewriter#232]
@frhagn - we are yet another grateful consumer of your handy package. thank you!

i was hoping to use [Humanizer](https://www.nuget.org/packages/Humanizer/) nuget package to do some automatic property name camelCasing... i thought it'd be simple `using Humanizer;` but it seems the TypeWriter template context is only aware of Microsoft, System & Typewriter namespaces.

Any help?

![image](https://user-images.githubusercontent.com/6301228/32116914-52ceb092-bb01-11e7-9218-d4a06e5bcba4.png)

**Comment by michaelaird** [comment]
Not sure if this is exactly related. I'd like to be able to share code between templates. ie. I'd like to be able to write my own helper methods that are reused across templates. This could be by writing a separate assembly that is referenced or (ideally) a .cs class that has access to the Typewriter types.

**Comment by rodro75** [comment]
Yes, that would be great!
I have a standard tst that I use in several solutions and what really change are a bunch of parameters.
Right now whenever I find some problem in my template I have to copy and paste the fix in dozens of files...

**Comment by info-lvsys** [comment]
Same here. It would be great to be able to add our own extensions to Typewriter, so we could centralize code

**Comment by TripleEmcoder** [comment]
Another idea would be to allow referencing/including other template files. A path relative to the current template would be fine for our use case. Allowing inclusion of templates relative to $(SolutionDir) would be ideal.

**Comment by rodro75** [comment]
@TripleEmcoder 
I'm working on that feature. Right now it works with both absolute and relative paths (relative to the current template) and I think that adding support for $(SolutionDir) or other variables wouldn't be a big deal.

There are still things to do before this can be considered a finished feature though.

Most important thing: you don't want your "partials" to be rendered by themselves, as they are meant to be included in some other file. So a different file extension should be introduced that benefits from the nice Roslyn-based editor as .tst does, but without rendering. 

Second thing: I don't have any experience with the VS extensibility model, so I couldn't manage to introduce a new token for this kind of directive and I just assumed that $Include(path) was enough. But I don't like it. The dollar sign is used for referencing methods. A more clean solution would be something like `#include "path"`, like `#include "$(SolutionDir)Client\templates\utility.tstp"`.
But we need to teach the editor that new syntax somehow.

I'll see what I can do.
Any help is apreciated of course :)

-rodro-

**Comment by pbarranis** [comment]
It sucks that the original feature request of the OP seems to have been lost by all the "I'd also likes".  Being able to import and use 3rd party libraries like Humanizer, MoreLinq, and many others would be invaluable in Typewriter.

**Comment by rodro75** [comment]
Hi @pbarranis ,

I actually implemented the original feature request and made a PR for it (#274).
Stay tuned!

-Rodro-

**Comment by pbarranis** [comment]
@rodro75 that's a god-send.  Thank you!

**Comment by pbarranis** [comment]
@rodro75 I hate to ask, but is there a simple example of how to get this working?  It took me a good amount of time just to sort through the PR and figure out whether the group had settled on "$Reference" or "#reference" from the PR discussion.  After about 3 hours of trying to get a one-line call to Humanizer's Humanize() call on an enum working, I had to give up and moving to pressing things.  Any sort of example would be hugely helpful.

On a side-note, referencing a DLL from a NuGet package appears to be a real pain-in-the-rear since it's not stored locally to the solution, which means each developer on the project could have it in a different place.  I didn't foresee that, unfortunately.

**Comment by PoyangLiu** [comment]
Great work @frhagn and @rodro75.  I just spent the last 3 days trying this out.  The C# code block makes it so extendable.  The only problem I have to workaround is the export path limited to the location of the tst file.

@pbarranis, you can create a csproj call `MyTypewriterHelper.csproj`.  a public static class `MyTypewriterHelper` with static method of `string GetImports(Class c) { ... }`.

In the template, do something like this, where the double tilda is the solution directory.  or use single tilda for project directory.
```
// tslint:disable
// This file is auto-generated. Do not modify.
#reference "~~\Path\Relative\To\Solution\MyTypewriterHelper.dll"
${
    using Typewriter.Extensions.Types;
    using MyTypewriterHelper;  // the namespace of your project

    Template(Settings settings) { settings.IncludeCurrentProject(); }

    string PrintTimestamp(File f) => string.Format("// Generated on {0:yyyy-MM-dd HH:mm:ss tt}", DateTime.Now);
    string Imports(Class c) => String.Join(Environment.NewLine, MyTypewriterHelper.GetImports(c));

}$PrintTimestamp
$Classes($HasExportToTypeScriptAttribute)[
$Imports

export interface $Name$TypeParameters$Inherit {
    $Properties[
    $Readonly$Name$Optional: $Type;]
    $Methods[
    $Name($Parameters[$name: $Type, ]): $Type;]
}]
```

**Comment by pbarranis** [comment]
@PoyangLiu Thank you for the attempt, though Typewriter is saying the using statement is invalid.  I can't imagine what I'm doing wrong, but maybe you can make heads or tails of this problem.  First, I'm running Typewriter 1.19.0 from 25-Jul-2018, and it's on the latest update of VS 2017 Pro.

Next, I grabbed a production copy of Humanizer.dll and put it in the root folder of my project; it's in the same folder of the .csproj file.  (Humanizer is a popular open-source project available through NuGet.)

Then, I updated the first few lines of my .tst file as follows:

```
#reference "~\Humanizer.dll";

${
  using Typewriter.Extensions.Types;
  using System.Text.RegularExpressions;
  using Humanizer;
```

The right side of the 'using' statement appears with a red line under it, and the following is in the Output window:

```
10:40:01.410 ERROR: Reference Error: System.IO.FileLoadException: The given assembly name or codebase was invalid. (Exception from HRESULT: 0x80131047)
   at System.Reflection.AssemblyName.nInit(RuntimeAssembly& assembly, Boolean forIntrospection, Boolean raiseResolveEvent)
   at System.Reflection.AssemblyName..ctor(String assemblyName)
   at Microsoft.VisualStudio.Platform.VsAppDomainManager.<GetAssemblyPaths>d__23.MoveNext()
   at Microsoft.VisualStudio.Platform.VsAppDomainManager.FindAssembly(String name, IEnumerable`1 probingPaths)
   at Microsoft.VisualStudio.Platform.VsAppDomainManager.InnerResolveHandler(String name)
   at Microsoft.VisualStudio.Platform.VsAppDomainManager.ResolveHandler(Object sender, ResolveEventArgs args)
   at System.AppDomain.OnAssemblyResolveEvent(RuntimeAssembly assembly, String assemblyFullName)
   at System.Reflection.AssemblyName.nInit(RuntimeAssembly& assembly, Boolean forIntrospection, Boolean raiseResolveEvent)
   at System.Reflection.RuntimeAssembly.CreateAssemblyName(String assemblyString, Boolean forIntrospection, RuntimeAssembly& assemblyFromResolveEvent)
   at System.Reflection.RuntimeAssembly.InternalLoad(String assemblyString, Evidence assemblySecurity, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean forIntrospection)
   at System.Reflection.RuntimeAssembly.InternalLoad(String assemblyString, Evidence assemblySecurity, StackCrawlMark& stackMark, Boolean forIntrospection)
   at System.Reflection.Assembly.Load(String assemblyString)
   at Typewriter.TemplateEditor.Lexing.Roslyn.ShadowClass.AddReference(String pathOrName)
   at Typewriter.Generation.TemplateCodeParser.ParseReference(Stream stream, ShadowClass shadowClass, ProjectItem templateProjectItem)
10:40:01.428 WARNING: Template error: CS0246 The type or namespace name 'Humanizer' could not be found (are you missing a using directive or an assembly reference?)
```

I'm 100% sure the file is in the place I've described, is a valid file that works in other projects, and the name matches exactly as described.  I run a normal x64 Windows OS and compile my projects with default 'bitness' settings.

I don't normally run VS in an elevated (UAC) configuration.  I ran it as Administrator just to check and see if that solved the problem, and I received exactly the same error.

What could possibly be the problem?  Any help would be greatly appreciated.

**Comment by PoyangLiu** [comment]
@pbarranis, I think what you are running into is a difference of framework.  Typewriter is built on .Net 4.5 with runtime dependency of 4.0.  Humanizer seems to be built on .Net core.

**Comment by pbarranis** [comment]
@PoyangLiu Thank you!  That at least answers this frustrating mystery.  My entire project is built on .NET Core 2.1.  Humanizer is actually built for .NET Standard, so it should work with both Core and Framework consuming libraries equally well.  This is disappointing :(

**Comment by michaelaird** [comment]
I wonder if the problem is the visual studio plugin hosting environment not
being able to load netstandard assemblies?
