### ISSUE TITLE
Typewriter throws exception: rror processing queue: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by marxxxx** [frhagn/Typewriter#243]
Since yesterday i get the following exception on every render and i can't figure out what the reason is.

```
10:36:34.587 ERROR: Error processing queue: Object reference not set to an instance of an object.
   at Typewriter.Generation.Template.FindProjectItem(String path)
   at Typewriter.Generation.Template.GetOutputPath(File file)
   at Typewriter.Generation.Template.SaveFile(File file, String output, Boolean& success)
   at Typewriter.Generation.Template.RenderFile(File file)
   at Typewriter.Generation.Controllers.GenerationController.<>c.<RenderFile>b__7_2(IFileMetadata fileMeta, Template template)
   at Typewriter.Generation.Controllers.GenerationController.<>c__DisplayClass12_1`1.<Enqueue>b__3(Template template)
   at Typewriter.Generation.Controllers.SolutionExtensions.ForEach[T](IEnumerable`1 items, Action`1 action)
   at Typewriter.Generation.Controllers.GenerationController.<>c__DisplayClass12_0`1.<Enqueue>b__2(String path, Int32 i)
   at Typewriter.Generation.Controllers.SolutionExtensions.ForEach[T](IEnumerable`1 items, Action`2 action)
   at Typewriter.Generation.Controllers.GenerationController.<>c__DisplayClass12_0`1.<Enqueue>b__1()
   at Typewriter.Generation.Controllers.EventQueue.ProcessQueue()

```

I tried to check for every null possible in my tst file but i guess this is not the reason for the problem.

My tst file looks like this:
```

${
    // Enable extension methods by adding using Typewriter.Extensions.*
    using Typewriter.Extensions.Types;

    // Uncomment the constructor to change template settings.
    Template(Settings settings)
    {
        settings.IncludeProject("MyProject.Models");
    }
}
${
    string ImportDeclarations(Class type)
    {
      List<string> imports = new List<string>();

      if(type != null)
      {
          if(type.Properties != null)
          {
              foreach(var property in type.Properties)
              {
                  if((!property.Type.IsPrimitive || property.Type.IsEnum) && property.Type.Name != type.Name )
                  {
                    imports.Add("import {" + GetBaseTypeName(property) + "} from './" + GetBaseTypeName(property) + "'; ");
                  }
              }
          }

          if(type.BaseClass != null)
          {
              imports.Add("import {" + type.BaseClass.Name + "} from './" + type.BaseClass.Name + "';");
          }
      }

      return string.Join(Environment.NewLine, imports.Distinct());
    }

    string GetBaseTypeName(Property property) 
    {
        if(property == null || property.Type == null || property.Type.Name == null)
            return string.Empty;
        return property.Type.Name.Replace("[]", string.Empty);
    }

    string GetTypeName(Property property) 
    {
        if(property == null || property.Type == null)
            return string.Empty;
        return property.Type.Name;
    }
}

${
    // https://github.com/frhagn/Typewriter/issues/36
    string ClassNameWithExtends(Class c) {
        if(c == null) return string.Empty;
        return c.Name +  (c.BaseClass!=null && c.BaseClass.Name != null ?  " extends " + c.BaseClass.Name : "");
    }
}

$Enums(*.Models)[
export enum $Name {
    $Values[$Name = $Value,
    ]
}]
$Classes(*.Models)[
$ImportDeclarations
export class $ClassNameWithExtends {
    $Properties[
    $name?: $GetTypeName;
    ]
}]

```

Thank you very much for your support!

**Comment by marxxxx** [comment]
Answering my own question:

The problem occurred after i moved the generation of the typescript files to a different project along with the generated .ts files and included them with "Include in Project" in the Visual Studio Project.

Typewriter obviously requires it's generated items to be in a special format in the csproj file so it recognizes which ones were auto-generated.

Solution was to delete every auto-generated File and rerun the generation for the whole project again.
