### ISSUE TITLE
Typewriter active development?

### ISSUE THREAD

**Issue by atotalnoob** [frhagn/Typewriter#290]
Is typewriter under active development anymore? 

If not, would you be open to me taking an active role in stewardship of typewriter?

My team at work uses typewriter everyday, it's an amazing tool and I would love to extend, add features, and continue to improve upon the great work that has already been completed.

**Comment by Sc0tTyXL** [comment]
@atotalnoob I don't think you guys are the only one :)

We've got two massive tst we are planning on open sourcing soon.

**Comment by atotalnoob** [comment]
What can I do to contribute? 

I'm assuming since there won't be any dependencies on the IDE, it will work in VSC as well?

**Comment by avilv** [comment]
if anyone's interested i released a small fork of typewriter, was mostly for self usage but why not share with this great community:
https://github.com/avilv/TypewriterX

its mostlys about adding more control over output
might tide you over till 2.0 is released here

**Comment by frhagn** [comment]
@atotalnoob nothing right now, but once I get the new version up on GitHub there'll probably be plenty :)
Yes, it's a dotnet core global cli tool so any editor will work, but initially I'm focusing on intellisense-support for Visual Studio and Visual Studio Code only.

**Comment by agustinbcu01** [comment]
I will love to help with the new version. the current one is useful, but the new features are very promising to us.

**Comment by atotalnoob** [comment]
@frhagn do you have a rough timeline/ETA? 

I'm not here to question your process, but you have a few developers that are actively trying to contribute... Why not use them?

**Comment by pavel-b-novikov** [comment]
Will it be polite to advise [Reinforced.Typings](https://github.com/reinforced/Reinforced.Typings) here? :)

**Comment by Christian-Schiffer** [comment]
> Excuse me, would it be polite to advise [Reinforced.Typings](https://github.com/reinforced/Reinforced.Typings) here? :) .NET Core support is already done year ago...

I looked at your generator and it looks great, not sure how it compares to TypeWriter though and since I already have implemented TypeWriter in my solution and its working well for me for ViewModels and controllers I likely won't be using yours for that at least. I might try your generator it for other generator tasks though, I am thinking of generating my c# repositories based on my models  Is that possible with your solution? Question: After only a quick and superficial look at your generator ... does your generator support custom templates or is everything controlled via attributes? I kind of think a dual approach would be the best way to go. Maybe you and frhagn can cooperate making a brand new project utilizing the best of two worlds? Cheers!

**Comment by pavel-b-novikov** [comment]
My generator gives to you full control over generated AST of TS output. So from one side it is little bit uncomfortable to control output. At the other side you almost do not have ability to generate invalid TS. By this approach you can generate Angular controllers from your classes, interfaces or everything you want. But - not via templates, yup. And also you have mentioned that you are going to generate C# repositories - it is also not possible because my framework can only generate TypeScript output.

**Comment by Christian-Schiffer** [comment]
> I use Attributes to query what needs to be outputted as well, it's the only way to get a lot of different functionality in one .tst.
> 
> I'm trying to open source my templates but I've had no success yet in my company.

Yeah I am considering to open source my templates too, yet I am uncertain if that is a good idea since I am unsure of how much of my projects business value is in those templates. I own the company so its my decision and I assure you, its not an easy one.

**Comment by pavel-b-novikov** [comment]
Well, okay. I will consider adding templates functionality to RT then. It would be nice if you'd give some examples of your templates to give me some thoughts regarding how do you use C#/TS generators _exactly_.

**Comment by atotalnoob** [comment]
@frhagn do you have any update?

**Comment by agustinbcu01** [comment]
@frhagn do you have any update?

**Comment by agustinbcu01** [comment]
@frhagn any update?

**Comment by GJGowey-biBerk** [comment]
@frhagn in 2.0 there should be a feature included to do roll up of all generated files into a single file or the ability to create an "index" file that includes references to all individually generated files.  The reason for this is that I'm running into a problem with webpack where it needs direct references to objects.  See my question on SO and the corresponding discussion at: [DTOs and webpack](https://stackoverflow.com/questions/56549360/webpack-errors-with-dto-objects-generated-from-typescript)

**Comment by agustinbcu01** [comment]
Other idea is Generate an nuGet Package for the code.model library, to make easy the external reference assembler feature. that helps building the reference every time the model changes.

**Comment by ReactiveThings** [comment]
@frhagn 
I have created Typewriter.CLI that is .NET Core Command Line Interface port of Typewriter. It has only some restrictions on IncludeCurrentProject, IncludeReferencedProjects and IncludeAllProjects options. I hope it will speed up work on Typewriter version 2.0
Please take a look https://github.com/ReactiveThings/Typewriter/tree/cli

**Comment by valantonini** [comment]
@ReactiveThings 

> I have created Typewriter.CLI that is .NET Core Command Line Interface port of Typewriter. It has only some restrictions on IncludeCurrentProject, IncludeReferencedProjects and IncludeAllProjects options. I hope it will speed up work on Typewriter version 2.0
Please take a look https://github.com/ReactiveThings/Typewriter/tree/cli

I'm having a lot of trouble getting this to work due to a problem trying to load System.Collections at runtime. I thought I would just need a binding redirect but can't figure it out. Am I missing something obvious? Here is the stack trace:


Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'System.Collections, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks, IntPtr ptrLoadContextBinder)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, IntPtr ptrLoadContextBinder)
   at System.Reflection.RuntimeAssembly.InternalLoad(String assemblyString, Evidence assemblySecurity, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean forIntrospection)
   at System.Reflection.RuntimeAssembly.InternalLoad(String assemblyString, Evidence assemblySecurity, StackCrawlMark& stackMark, Boolean forIntrospection)
   at System.Reflection.Assembly.Load(String assemblyString)
   at Typewriter.TemplateEditor.Lexing.Roslyn.ShadowWorkspace.AddProjectWithDocument(String documentFileName, String text) in C:\Source\Github\Typewriter.Cli\src\Typewriter\TemplateEditor\Lexing\Roslyn\ShadowWorkspace.cs:line 57
   at Typewriter.TemplateEditor.Lexing.Roslyn.ShadowClass..ctor() in C:\Source\Github\Typewriter.Cli\src\Typewriter\TemplateEditor\Lexing\Roslyn\ShadowClass.cs:line 52
   at Typewriter.Generation.TemplateCodeParser.Parse(TemplateInfo templateProjectItem, String template, List`1 extensions) in C:\Source\Github\Typewriter.Cli\src\Typewriter\Generation\TemplateCodeParser.cs:line 28
   at Typewriter.Generation.Template.<LazyTemplate>b__12_0() in C:\Source\Github\Typewriter.Cli\src\Typewriter\Generation\Template.cs:line 93
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at Typewriter.Generation.Template.<LazyConfiguration>b__11_0() in C:\Source\Github\Typewriter.Cli\src\Typewriter\Generation\Template.cs:line 61
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at Typewriter.Generation.Template.get_Settings() in C:\Source\Github\Typewriter.Cli\src\Typewriter\Generation\Template.cs:line 29
   at Typewriter.CLI.Typewriter.Generate(String solutionPath, String projectPath, IEnumerable`1 templatePaths, BuildOptions buildOptions) in C:\Source\Github\Typewriter.Cli\Typewriter.CLI\Typewriter.cs:line 41
   at Typewriter.CLI.Program.Run(Options options) in C:\Source\Github\Typewriter.Cli\Typewriter.CLI\Program.cs:line 47
   at Typewriter.CLI.Program.<>c.<Main>b__0_0(Options options) in C:\Source\Github\Typewriter.Cli\Typewriter.CLI\Program.cs:line 36
   at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Action`1 action)
   at Typewriter.CLI.Program.Main(String[] args) in C:\Source\Github\Typewriter.Cli\Typewriter.CLI\Program.cs:line 35

**Comment by agustinbcu01** [comment]
@valantonini 
I'm got the same issue, My work around was:
Create the method on the template and call it. and returns IEnumerable avoiding dictionaries or similar.
It is not ideal but works.

**Comment by valantonini** [comment]
@agustinbcu01 

Thanks for the response. I don't think that will work for my particular case but I've found targeting coreapp2.1 or coreapp2.2 fixes the collections issue and it will work with enums but I'm now faced with the below when trying to run a template that deals with objects:

info: [0]
      Builded 6 projects
warn: [0]
      Template error: CS0012 The type 'Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.
fail: [0]
      The type 'Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.
warn: [0]
      Template error: CS0012 The type 'Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.

fail: [0]
      The type 'Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.
warnUnhandled Exception: : [0]
      Template error: CS0012 The type 'Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.
fail: [0]
      The type 'Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.
warn: [0]
      Template error: CS0012 The type 'Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.
fail: [0]
      The type 'Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.
warn: [0]
      Template error: CS0012 The type 'Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.
fail: [0]
      The type 'Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.
warn: [0]
      Template error: CS0012 The type 'Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.
fail: [0]
      The type 'Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.
System.Exception: Failed to compile template.
   at Typewriter.Generation.Compiler.Compile(ShadowClass shadowClass) in C:\Source\Github\Typewriter.Cli\src\Typewriter\Generation\Compiler.cs:line 79
   at Typewriter.Generation.TemplateCodeParser.Parse(TemplateInfo templateProjectItem, String template, List`1 extensions) in C:\Source\Github\Typewriter.Cli\src\Typewriter\Generation\TemplateCodeParser.cs:line 44
   at Typewriter.Generation.Template.<LazyTemplate>b__12_0() in C:\Source\Github\Typewriter.Cli\src\Typewriter\Generation\Template.cs:line 85
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at Typewriter.Generation.Template.<LazyConfiguration>b__11_0() in C:\Source\Github\Typewriter.Cli\src\Typewriter\Generation\Template.cs:line 61
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at Typewriter.Generation.Template.get_Settings() in C:\Source\Github\Typewriter.Cli\src\Typewriter\Generation\Template.cs:line 29
   at Typewriter.CLI.Typewriter.Generate(String solutionPath, String projectPath, IEnumerable`1 templatePaths, BuildOptions buildOptions) in C:\Source\Github\Typewriter.Cli\Typewriter.CLI\Typewriter.cs:line 41
   at Typewriter.CLI.Program.Run(Options options) in C:\Source\Github\Typewriter.Cli\Typewriter.CLI\Program.cs:line 42
   at Typewriter.CLI.Program.<>c.<Main>b__0_0(Options options) in C:\Source\Github\Typewriter.Cli\Typewriter.CLI\Program.cs:line 33
   at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Action`1 action)
   at Typewriter.CLI.Program.Main(String[] args) in C:\Source\Github\Typewriter.Cli\Typewriter.CLI\Program.cs:line 32

**Comment by ReactiveThings** [comment]
@valantonini It looks it doesn't work on Linux with .net core 2.0. I have updated it to .net core 2.1 and tested on docker image microsoft/dotnet:2.1-sdk. Please get the latest changes and check if it fixed your issue.

**Comment by ReactiveThings** [comment]
@valantonini I see that you have another issue. Can you prepare a template that reproduce the error?

**Comment by valantonini** [comment]
@ReactiveThings 

Thanks, will do. It's a pretty complicated template using a dll we created that I can't post publicly. I will try to replicate the problem with a simplified version.

**Comment by ReactiveThings** [comment]
@valantonini Have you compiled dll with .NET Standard 2.0 target and reference to the new Typewriter.CodeModel?

**Comment by valantonini** [comment]
@ReactiveThings Thanks very much.

Changing to a Typewriter.CodeModel appears to work. It worked perfectly for 2 fairly complicated projects. I am having trouble now with 1 final project that is just enums.

If I look at the Microsoft.CodeAnalysis.Workspaces.Projects in the RenderProject method in Typewriter.cs with the debugger, it says there are 0 documents. Any ideas?

**Comment by ReactiveThings** [comment]
@valantonini Please check if files have target Compile. Please also try to run with -c parameter and without -d

**Comment by valantonini** [comment]
@ReactiveThings The -c option fixed my problems. Thank you so much for all your help and the awesome project. We can finally make test generation part of the build pipeline.

For those having issues here are some of the mistakes I made:

- The --project is the project that contains the C# files to transpile not the project the .tst file resides in (if they live in different projects)
- I had to use the `--clean` option _not_ the default `--design-time` option (some of the symptoms of this were there were no templates being rendered and if you look at the Microsoft.CodeAnalysis.Workspaces.Projects variable in the Typewriter.cs>RenderProject method in the debugger you will see hasDocuments == false and no documents in the collection)
- I use a custom dll in the .tst templates referenced using the `#reference "~~\path\library.dll` syntax. I had to recompile these using the dll generated from @ReactiveThings project

Legendary stuff!

**Comment by pavangayakwad** [comment]
Dear @frhagn, thanks for the tool. Any updates on the complete re-write and when you are planning rollout? The existing tool lacks properly recognizing enums and partial classes.

**Comment by s4m0r4m4** [comment]
Hello @frhagn, just checking in to see how 2.0 is coming along. I haven't seen much public activity lately and it seems like you have folks here willing to help.  

I've even seen forks starting to appear from this library (https://avilv.github.io/TypewriterX/, https://github.com/ReactiveThings/Typewriter/tree/cli). Perhaps its time to go public even with 2.0 incomplete so others can contribute and we can keep everybody on the same path. Thanks for this open source project, it has provided much help to my work!
