### ISSUE TITLE
Array.IsPrimitive with Roslyn throws nullreference exception

### ISSUE THREAD

**Issue by johannordin** [frhagn/Typewriter#56]
If I have an array (`[]`) type in my C#-code an try to access `$Type.IsPrimitive` in VS 2015 i get the following exception: 
```System.NullReferenceException: Object reference not set to an instance of an object.
   at Typewriter.Metadata.Roslyn.Extensions.GetFullName(ISymbol symbol)
   at Typewriter.Metadata.Roslyn.Extensions.GetFullName(ISymbol symbol)
   at Typewriter.Metadata.Roslyn.RoslynTypeMetadata.get_FullName()
   at Typewriter.CodeModel.Helpers.IsPrimitive(ITypeMetadata metadata)
   at Typewriter.CodeModel.Implementation.TypeImpl.get_IsPrimitive()
   at __Typewriter.__Code.<>c.<DataParameter>b__8_0(Parameter p)
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at __Typewriter.__Code.DataParameter(Method m)```

Any type of Array seems to reproduce this problem.

**Comment by frhagn** [comment]
Resolved by PR #57
