### ISSUE TITLE
Best way to keep templates out of source control

### ISSUE THREAD

**Issue by cwoolum** [frhagn/Typewriter#61]
Hey Guys,

I've been playing with the templates a bit and I've run into a small issue. The files generated by the templates get picked up by TFS and after checking them in, the templates can no longer modify them unless you manually check all of the generated files out. 

What would be a better approach; trying to create a .tfignore or have Typewriter check out files before updating them? I'm trying to roll this out to our entire development team so the less manual work and training we need to do, the easier we can adopt.

**Comment by frhagn** [comment]
Hm, interesting problem. I've used Typewriter in a couple of TFS projects without any issues, but only using local workspaces.
This is definetly someting Typewriter should handle seamlessly, I'll try to reproduce the issue, it would be great if you could you provide som more details on your dev setup? E.g. Visual Studio version, TFS version, workspace type (local oc server).

**Comment by cwoolum** [comment]
Visual Studio 2015
TFS 2013
Server Workspace

**Comment by cwoolum** [comment]
Here's an exception
```
10:23:09 ERROR: Render Exception: Access to the path 'C:\**scrubbed**.ts' is denied.,    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalWriteAllText(String path, String contents, Encoding encoding, Boolean checkHost)
   at System.IO.File.WriteAllText(String path, String contents)
   at Typewriter.Generation.Template.SaveFile(String path, String output, Boolean saveProjectFile)
   at Typewriter.Generation.Template.RenderFile(File file, Boolean saveProjectFile)
   at Typewriter.Generation.Controllers.GenerationController.Render(GenerationEvent generationEvent)
```

**Comment by frhagn** [comment]
Thanks Chris!
I was able to reproduce the issue, and as I suspected it's related to the TFS Server Workspace. When using a server workspace checked-in files are marked as read-only and needs to be checked out before they can be edited. 
I've added a check-out function in Typewriter that seems to resolve the issue, but I need to do some more testing before I publish it.

**Comment by cwoolum** [comment]
Aah, awesome! Thanks!

**Comment by frhagn** [comment]
I just published Typewriter 1.1 that should resolve the issue. Please give it a try :)

**Comment by cwoolum** [comment]
Works! Thanks!

**Comment by gregveres** [comment]
Do people generally let source control check in these files? I am using Git and I was going to try to put the output in a different directory and then have Git ignore that directory.

**Comment by cwoolum** [comment]
I have been checking them in. If you do CI, I don't think these would get
recreated...

**Comment by gregveres** [comment]
Hmm that is an interesting point. Right now I am using Visual Studio Online as my CI server. I think you are expecting these to not be recreated because the CI server doesn't have Typewriter installed and even if it did, typewriter isn't part of the MSBuild chain so it wont get called. 

That makes sense to me. Checking them in it is then. 

Thanks for pointing that out.
Greg
